### ISSUE TITLE
localhost/login.php error

### ISSUE THREAD

**Issue by himalimehta** [phuselab/DANTE#1]
I'm stuck at the following part of installation for DANTE: Open the browser to the page http://localhost/login.php or wherever you installed DANTE.

For reference, I have already edited the config.php file according to the environment, as seen below:
`<?php
$GLOBALS = array(
    'db_host' => 'localhost',
    'db_name' => 'dante',
    'db_user' => 'root',
    'db_pass' => 'notprovided4privacy',
    'anno_rate' => '25',    // get a value every 1/anno_rate seconds
    'save_mode' => 'db'); // db or file
?>`

For the db_host, I have also tried 'localhost:8008' since my Apache server is running on that. For example, when I type 'localhost:8008/" in my browser, the output is: "It works!" but when I type 'localhost:8008/login.php' I get the following error: "Not Found - The requested URL was not found on this server." 

Does anyone have any suggestions on what I should change to make sure the localhost is up and running?

**Comment by himalimehta** [comment]
I have figured out how to get the localhost running by downloading WAMP and Visual C++ to my C: drive. I then copied all the files from the dante folder to the "www" folder inside the WAMP64 folder.

**Comment by vcuculo** [comment]
Thanks for reporting @himalimehta. Glad you solved it!
