### ISSUE TITLE
Login error on localhost

### ISSUE THREAD

**Issue by himalimehta** [phuselab/DANTE#2]
I keep getting the following error, even though I am using the same username and password that I edited in my config.php file: "Error: Username or password is not correct."

Additionally, I get the following warnings on the localhost page:

1. Warning: mysqli_connect(): (HY000/2002): No connection could be made because the target machine actively refused it. in C:\wamp64\www\model.php on line 179
2. Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in C:\wamp64\www\model.php on line 181
3. Warning: mysqli_close() expects parameter 1 to be mysqli, bool given in C:\wamp64\www\model.php on line 182
4. Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, null given in C:\wamp64\www\login.php on line 11

Does anyone know a solution to these warnings so that I can log in?

**Comment by vcuculo** [comment]
@himalimehta please check the name of the database where you imported the `annotationdb.sql` file. The default is `annotationdb` and this should reflect the `db_name` parameter in `config.php` file.

**Comment by vcuculo** [comment]
@himalimehta we just pushed a new version of the software, please try the new version following the updated installation instructions.

**Comment by vcuculo** [comment]
I close this since it seems solved, as reported in #3
