### ISSUE TITLE
Annotation for Categorical emotions

### ISSUE THREAD

**Issue by himalimehta** [phuselab/DANTE#5]
@vcuculo hi, after converting my videos to mp4 format I am finally able to annotate them in terms of valence and arousal by using DANTE. 

Since valence and arousal are considered as dimensional labels, is there a way to use DANTE to annotate the categorical emotions (happy, sad, anger, neutral, fear, disgust, and surprised) as well, in addition to already annotating the valence and arousal? I have attached a .png file of some other annotation tool which has this option, for reference:

![annotationtool](https://user-images.githubusercontent.com/77561854/108575786-62795f80-72e9-11eb-98d3-a8a82f8172de.png)

**Comment by vcuculo** [comment]
dear @himalimehta glad that you were able to use DANTE (I will close #4 ).

About your feature request, unfortunately is not currently planned to support categorical annotation, but with a basic knowledge of PHP you can easily include such feature. Thanks!

**Comment by himalimehta** [comment]
@vcuculo thank you, I will try it. To clarify, do you mean to say I can include this feature to DANTE? If so, which file .php should I edit in order to add such a feature?

**Comment by vcuculo** [comment]
oh yes @himalimehta , it's opensource, so you can edit as you prefer as long as you follow the [LICENSE](https://github.com/phuselab/DANTE/blob/master/LICENSE). The main points of intervention should be :

- index.php for the UI (view)
- saveAnnotation.php for the save function (controller)
- model.php and annotationdb.sql for the data storage (model)

**Comment by himalimehta** [comment]
@vcuculo I will try it. Thanks again for all your help!
